---
title: "Analysis RDC data"
author: "Niko Speybroeck"
date: "2025-09-14"
output:
  html_document:
    theme: journal
    code_folding: hide
---

```{r setup, include=FALSE}
library(openxlsx)
library(tableone)
library(dplyr)
library(knitr)
library(kableExtra)
library(ggplot2)
library(data.table)
library(haven)
library(here)
library(ranger)
library(fastshap)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, dpi = 500)
```


## RDC Analysis (Congo Example)

```{r}

remove(list=ls())	# remove any existing list or vector
library(foreign)	# necessary to import the Stata file
source(here("R", "functions.R"))

all <- readRDS(here("prev_analysis", "RDC_DHS_2007.rds"))

# to have children <5 only (same as taking the file "Children's Recode") 
all$agech<-all$v008-all$b3	
all<-subset(all, agech<60)

# define variables and categories



# Respondent's basic data

# 1. Define vectors for renaming
old_nms_respondents <- c(
  "v000", "v001", "v002", "v003", "v005", "v007", "v008", 
  "v011", "v021", "v101", "v102", "v130", "v131", "v133", 
  "v134", "v149", "v190", "v191"
)

new_nms_respondents <- c(
  "countrycode", "cluster", "household", "mother", "weight", 
  "studyyear", "dateinterview", "datebirthmother", "PSU", 
  "region", "typeresidence", "religion", "ethnicity", 
  "educyears", "placeresidence", "educlevel", "quintile", "wealth"
)

# 2. Define labels based on comments
labels_respondents <- c(
  "e.g. CD5 = Congo Democratic Republic",
  "sample point",
  "household number",
  "number in the household",
  "sample weight + 6 decimals",
  "year of interview",
  "date of interview (century month code)",
  "date of birth (CMC)",
  "primary sampling unit (~cluster)",
  "region of residence",
  "type of place of residence (urban/rural)",
  "country-specific",
  "country-specific",
  "education in single years",
  "large cities/small cities/towns/countryside",
  "educational achievement",
  "wealth quintiles",
  "wealth index factor score + 5 decimals"
)

# 3. Apply renaming by reference
setnames(all,
  old = old_nms_respondents,
  new = new_nms_respondents, skip_absent = TRUE
)

# 4. Apply labels to the new column names


set_col_labels <- function(data, col_names, labels) {
  for (i in seq_along(col_names)) {
    col_name <- col_names[i]
    # Check if column exists
    if (col_name %in% names(data)) {
      setattr(data[[col_name]], "label", labels[i])
    }
  }
}


set_col_labels(all, new_nms_respondents, labels_respondents)

# Reproduction: each respondent's 
#child (up to 20) ordered in reverse order such as the 


# last birth is given first 

old_nms_child <- c("b3", "b4", "b5", "b7", "b11")
new_nms_child <- c(
  "datebirthchild", "sex",
  "alive", "agedeath", "birthinterval"
)

labels_child <- c(
  "date of birth (CMC)",
  "sex",
  "child alive or not at the time of interview",
  "age at death of the child in completed months",
  "preceding birth interval (except first birth)"
)

# Apply renaming by reference
setnames(all,
  old = old_nms_child,
  new = new_nms_child, skip_absent = TRUE
)

# Apply labels
set_col_labels(all, new_nms_child, labels_child)


# Maternity: relate to births in the three/five years preceding interview
old_nms_maternity <- c(
  "m2a", "m2b", "m3a",
  "m3b", "m5", "m14", "m19", "h9", "hw3", "hw70"
)

new_nms_maternity <- c(
  "ancdoctor", "ancnurse", "doctor", "nurse", "breastfeeding",
  "ancvisits", "birthweight", "measles", "height", "zscore"
)

labels_maternity <- c(
  "prenatal care (anc) by a doctor",
  "prenatal care by a nurse or midwife",
  "delivery assisted with a doctor",
  "delivery assisted with a nurse or midwife",
  "duration of breastfeeding in months",
  "number of anc visits during pregnancy",
  "weight of child at birth in kg + 3 decimals",
  "received measles vaccination",
  "height in cm + 1 decimal",
  "height-for-age standard deviation (WHO)"
)

# Apply renaming by reference
setnames(all,
  old = old_nms_maternity,
  new = new_nms_maternity, skip_absent = TRUE
)

# Apply labels
set_col_labels(all, new_nms_maternity, labels_maternity)

# + 2 decimals


# Other health issues
old_nms_health <- c("v481")
new_nms_health <- c("insurance")
labels_health <- c("covered by health insurance")

setnames(all, old = old_nms_health, 
new = new_nms_health, skip_absent = TRUE)
set_col_labels(all, new_nms_health, labels_health)


# Marriage of the respondent
old_nms_marriage <- c("v501", "v502", "v504")
new_nms_marriage <- c("maritalstatus", "marriedcurrent", "livewithpartner")
labels_marriage <- c(
  "current marital status",
  "currently, formerly, or never married",
  "the partner lives in the household"
)

setnames(all, old = old_nms_marriage, 
new = new_nms_marriage, skip_absent = TRUE)
set_col_labels(all, new_nms_marriage, labels_marriage)


# Partner's characteristics (ever-married women) and woman's work
old_nms_partner <- c("v704", "v705",
 "v715", "v717", "v729", "v731")
new_nms_partner <- c(
  "pemployed", "poccup", "peducyears", "moccup", "peduclevel", "employed"
)

labels_partner <- c(
  "current/last partner's most recent occupation",
  "standardised partner's occupation groups",
  "most recent partner's education in years",
  "standardised respondent's occupation groups",
  "educational achievement of the partner",
  "the respondent worked in the last 12 months"
)

setnames(all,
  old = old_nms_partner,
  new = new_nms_partner, skip_absent = TRUE
)
set_col_labels(all, new_nms_partner, labels_partner)


```





```{r}
#preparation of variables

# define variables' categories and calculate indicators
# "a,b,c,d..." are added before some categories to order it and specify the reference for 
# the regression analysis 

# sampling weights must be divided by 1000000 (6 decimals) 
all$weight<-all$weight/1000000 

# Wealth and quintiles
# wealth must be divided by 100000 (5 decimals) 
all$wealth<-all$wealth/100000 
all$quint<-NULL
all$quint[all$quintile==1]<-"b low"
all$quint[all$quintile==2]<-"b low"
all$quint[all$quintile==3]<-"a high"
all$quint[all$quintile==4]<-"a high"
all$quint[all$quintile==5]<-"a high"

# Country, regions and type of residence
all$country<-as.factor(all$countrycode)
all$countryc<-as.numeric(all$country)
all$country<-NULL
all$country[all$countryc==1]<-"DRCongo"

all$country<-as.factor(all$country)
all$region[all$country=="DRCongo"&all$region==10]<-1
all$region[all$country=="DRCongo"&all$region==20]<-2
all$region[all$country=="DRCongo"&all$region==30]<-3
all$region[all$country=="DRCongo"&all$region==40]<-4
all$region[all$country=="DRCongo"&all$region==50]<-5
all$region[all$country=="DRCongo"&all$region==61]<-6
all$region[all$country=="DRCongo"&all$region==62]<-7
all$region[all$country=="DRCongo"&all$region==63]<-8
all$region[all$country=="DRCongo"&all$region==70]<-9
all$region[all$country=="DRCongo"&all$region==80]<-10
all$region[all$country=="DRCongo"&all$region==90]<-11

all$rural<-NULL
all$rural[all$typeresidence==1]<-0
all$rural[all$typeresidence==2]<-1

all$region<-as.numeric(all$region)
all$reg<-NULL
all$reg[all$country=="DRCongo"&all$region==1]<-"Kinshasa"
all$reg[all$country=="DRCongo"&all$region==2]<-"Bas-Congo"
all$reg[all$country=="DRCongo"&all$region==3]<-"Bandundu"
all$reg[all$country=="DRCongo"&all$region==4]<-"Equateur"
all$reg[all$country=="DRCongo"&all$region==5]<-"Orientale"
all$reg[all$country=="DRCongo"&all$region==6]<-"Nord-Kivu"
all$reg[all$country=="DRCongo"&all$region==7]<-"Maniema"
all$reg[all$country=="DRCongo"&all$region==8]<-"Sud-Kivu"
all$reg[all$country=="DRCongo"&all$region==9]<-"Katanga"
all$reg[all$country=="DRCongo"&all$region==10]<-"Kasai Oriental"
all$reg[all$country=="DRCongo"&all$region==11]<-"Kasai Occidental"

# Parent's education and occupation
all$educlev<-NULL
all$educlev[all$educlevel==0]<- "f no education"
all$educlev[all$educlevel==1]<- "e inc.primary"
all$educlev[all$educlevel==2]<- "d primary"
all$educlev[all$educlevel==3]<- "c inc.secondary"
all$educlev[all$educlevel==4]<- "b secondary"
all$educlev[all$educlevel==5]<- "a higher"
all$educlev[all$educlevel==8]<- NA
all$educlev[all$educlevel==9]<- NA
all$ed<-NULL
all$ed[all$educlevel==0]<- "b no education"
all$ed[all$educlevel==1]<- "b no education"
all$ed[all$educlevel==2]<- "a education"
all$ed[all$educlevel==3]<- "a education"
all$ed[all$educlevel==4]<- "a education"
all$ed[all$educlevel==5]<- "a education"
all$ed[all$educlevel==8]<- NA
all$ed[all$educlevel==9]<- NA
all$peduclev<-NULL
all$peduclev[all$peduclevel==0]<- "f no education"
all$peduclev[all$peduclevel==1]<- "e inc.primary"
all$peduclev[all$peduclevel==2]<- "d primary"
all$peduclev[all$peduclevel==3]<- "c inc.secondary"
all$peduclev[all$peduclevel==4]<- "b secondary"
all$peduclev[all$peduclevel==5]<- "a higher"
all$peduclev[all$peduclevel==8]<- NA
all$peduclev[all$peduclevel==9]<- NA
all$ped<-NULL
all$ped[all$peduclevel==0]<- "b no education"
all$ped[all$peduclevel==1]<- "b no education"
all$ped[all$peduclevel==2]<- "a education"
all$ped[all$peduclevel==3]<- "a education"
all$ped[all$peduclevel==4]<- "a education"
all$ped[all$peduclevel==5]<- "a education"
all$ped[all$peduclevel==8]<- NA
all$ped[all$peduclevel==9]<- NA
all$educyears[all$educyears>90]<-NA
all$peducyears[all$peducyears>90]<-NA
all$moccup[all$employed==0]<-0
all$mocc<-NULL
all$mocc[all$moccup==0]<-"c Household, unskilled manual, not working"
all$mocc[all$moccup==1]<-"a other"
all$mocc[all$moccup==2]<-"a other"
all$mocc[all$moccup==3]<-"a other"
all$mocc[all$moccup==4|all$moccup==5|all$moccup==10]<-"d Agriculture"
all$mocc[all$moccup==6]<-"c Household, unskilled manual, not working"
all$mocc[all$moccup==7]<-"a other"
all$mocc[all$moccup==8]<-"a other"
all$mocc[all$moccup==9]<-"c Household, unskilled manual, not working"
all$mocc[all$moccup==96]<-"a other"
all$mocc[all$moccup==97]<-"c Household, unskilled manual, not working"
all$mocc[all$moccup>=98]<-NA
all$poccup[all$pemployed==0]<-0
all$pocc<-NULL
all$pocc[all$poccup==0]<-"c Household, unskilled manual, not working"
all$pocc[all$poccup==1]<-"a other"
all$pocc[all$poccup==2]<-"a other"
all$pocc[all$poccup==3]<-"a other"
all$pocc[all$poccup==4|all$poccup==5|all$poccup==10]<-"d Agriculture"
all$pocc[all$poccup==6]<-"c Household, unskilled manual, not working"
all$pocc[all$poccup==7]<-"a other"
all$pocc[all$poccup==8]<-"a other"
all$pocc[all$poccup==9]<-"c Household, unskilled manual, not working"
all$pocc[all$poccup==96]<-"a other"
all$pocc[all$poccup==97]<-"c Household, unskilled manual, not working"
all$pocc[all$poccup>=98]<-NA

# mother's age and marital status
all$agemother<-NULL
all$agemother<-(all$datebirthchild-all$datebirthmother)/15
all$agemother<-as.integer(all$agemother)
all$agemoth<-NULL
all$agemoth[all$agemother<20]<-"less than 20"
all$agemoth[all$agemother>=20]<-"a20 or more"
all$agemoth<-as.factor(all$agemoth)
all$maritalstatus[all$maritalstatus==0]<-"never married"
all$maritalstatus[all$maritalstatus==1]<-"married"
all$maritalstatus[all$maritalstatus==2]<-"living together"
all$maritalstatus[all$maritalstatus==3]<-"widowed"
all$maritalstatus[all$maritalstatus==4]<-"divorced"
all$maritalstatus[all$maritalstatus==5]<-"not living together"
all$maritalstatus[all$maritalstatus==9]<-NA
all$married<-NULL
all$married[all$marriedcurrent==1]<-1
all$married[all$marriedcurrent==0]<-0
all$married[all$marriedcurrent==9]<-NA

# Child characteristics
all$male<-NULL
all$male[all$sex==1]<-1
all$male[all$sex==2]<-0
all$birthw<-NULL
all$birthw[all$birthweight>=9000]<-NA
all$lowbirthw<-NULL
all$lowbirthw[all$birthw<2500]<-1
all$lowbirthw[all$birthw>=2500]<-0
all$agechild<-NULL
all$agechild<-all$dateinterview - all$datebirthchild
all$birth<-NULL
all$birth[all$bord==1]<-"a first"
all$birth[(all$bord==2|all$bord==3|all$bord==4)&all$birthinterval<24]<-"b 2-4 short"
all$birth[(all$bord==2|all$bord==3|all$bord==4)&all$birthinterval>=24]<-"c 2-4 long"
all$birth[all$bord>4&all$birthinterval<24]<-"d 5+ short"
all$birth[all$bord>4&all$birthinterval>=24]<-"e 5+ long"
all$deadu5<-NULL
all$deadu5[all$alive==0 &all$agedeath<60]<-1
all$deadu5[all$alive==1]<-0
all$deadu1<-NULL
all$deadu1[all$alive==0 &all$agedeath<12]<-1
all$deadu1[all$alive==1|all$agedeath>=12]<-0
all$zscore<-all$zscore/100		# zscore must be divided by 100 (2 decimals) 
all$vmeasles<-NULL
all$vmeasles[all$measles==0]<-0
all$vmeasles[all$measles==1|all$measles==2 | all$measles==3]<-1

# Birth characteristics
all$anc<-NULL
all$anc[(all$ancdoctor==0&all$ancnurse==0)]<-"b no or few skilled anc"
all$anc[(all$ancvisits>=1&all$ancvisits<4)&	
          (all$ancdoctor==1|all$ancnurse==1)]<-"b no or few skilled anc"
all$anc[(all$ancvisits>=4&all$ancvisits<98)&
          (all$ancdoctor==1|all$ancnurse==1)]<-"a 4+ skilled anc"
all$unskilled<-NULL
all$unskilled[all$doctor==0&all$nurse==0]<-1
all$unskilled[all$doctor==1|all$nurse==1]<-0
all$skilled<-NULL
all$skilled[all$doctor==0&all$nurse==0]<-0
all$skilled[all$doctor==1|all$nurse==1]<-1
all$breastfed<-NULL
all$breastfed[all$breastfeeding<=6]<- "<=6 months"
all$breastfed[all$breastfeeding>6&all$breastfeeding<93]<- ">6 months"
all$breastfed[all$breastfeeding==94]<-"never breastfed"
all$breastfed[all$breastfeeding>=95]<-NA
all$breast<-NULL
all$breast[all$breastfeeding<=93]<- 1
all$breast[all$breastfeeding==94]<-0
all$breast[all$breastfeeding>=95]<-NA

# change variables' type for the regression analysis

all$caseid<-as.factor(all$caseid)
all$countryc<-as.factor(all$countryc)
all$cluster<-as.integer(all$cluster)
all$household<-as.integer(all$household)
all$mother<-as.integer(all$mother) 
all$studyyear<-as.factor(all$studyyear)
all$PSU<-as.integer(all$PSU)
all$quint<-as.factor(all$quint)
all$quintile<-as.factor(all$quintile)
all$educyears<-as.integer(all$educyears)
all$agedeath<-as.integer(all$agedeath)
all$male<-as.logical(all$male)
all$ed<-as.factor(all$ed)
all$ped<-as.factor(all$ped)
all$wealth<-as.numeric(all$wealth)
all$region<-as.factor(all$region)
all$reg<-as.factor(all$reg)
all$rural<-as.logical(all$rural)
all$mocc<-as.factor(all$mocc)
all$pocc<-as.factor(all$pocc)
all$anc<-as.factor(all$anc)
all$birth<-as.factor(all$birth)
all$deadu5<-as.logical(all$deadu5)
all$maritalstatus<-as.factor(all$maritalstatus)
all$employed<-as.factor(all$employed)
all$moccup<-as.factor(all$moccup)
all$vmeasles<-as.logical(all$vmeasles)
all$unskilled<-as.logical(all$unskilled)
all$skilled<-as.logical(all$skilled)
all$breastfed<-as.factor(all$breastfed)
all$agechild<-as.integer(all$agechild)

# subset of children with no NA for deadu5
all<-subset(all, deadu5==T |deadu5==F)

DRCongo<-all[,c("caseid","deadu5","agechild", "wealth","quint", "quintile","unskilled", 
             "male", "birth","agemoth", "rural", "region","reg", "ed","ped", "mocc", "pocc", "PSU", 
             "household","country","weight")]


DRCongo <- na.omit(DRCongo)

setDT(DRCongo)

save(DRCongo, file = here("data", "DRCongo.rda"))

###################################################################### survey design
library(survey)
my.svydesign2 <- function(data ){ 
  name=paste(deparse(substitute(data)),'.dta')
  write.dta(data,file=name)
  svydesign(id=as.formula("~PSU+household"), weight=as.formula("~weight"),data=data)
}

####################################################################################### analyses
# descriptive analysis with the survey design
options(digits=2)

# This should give the decomposition results for RDC (second appearance for C) in Table 3 https://jech.bmj.com/content/67/8/667
rownames(DRCongo) = NULL ### HERE 




DRCongoc<-my.svydesign2(DRCongo)

# table(DRCongo$deadu5 )
fmla <- "as.numeric(deadu5) ~ quint + unskilled + male + birth + agemoth + rural + 
  ed + ped + mocc + pocc + region"
m<-svyglm( as.formula(fmla),DRCongoc, family=quasibinomial, data=DRCongo)

# m<-glm( as.formula(fmla),family=quasibinomial, data=DRCongo)

summary(svyglm(as.formula(fmla),DRCongoc, family=quasibinomial))$coef %>%
 kable("html", caption = "Coeffcients Table 2 in https://jech.bmj.com/content/67/8/667") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

# devtools::install_github("kdevkdev/rineq")

library(rineq)
```

```{r results='hide'}
# This is the one!!
sink(tempfile())
c<-rineq::contribution(m,DRCongo$wealth)	
summary <- as.data.frame(summary(c))
summary$Corrected <- NULL

df <- as.data.frame(summary(c))

sink()
```

```{r}
summary %>%
 kable("html", caption = "Decomposition Contributions (WDW) Table 3 in https://jech.bmj.com/content/67/8/667") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

# plot(c, decreasing = FALSE, horiz = TRUE)

# Extract the summary into a data frame
df$Variable <- rownames(df)  # add variable names as a column

# remove rows like 'residual' if desired
df <- subset(df, Variable != "residual")

# Arrange variables by Contribution (%)
df <- df[order(df$`Contribution (%)`), ]  # increasing order
df$Variable <- factor(df$Variable, levels = df$Variable) # preserve ordering

ggplot(df, aes(x = `Contribution (%)`, y = Variable)) +
  geom_col(fill = "steelblue") +
  geom_vline(xintercept = 0, color = "black", linewidth = 0.5) +
  labs(
    title = "Decomposition of Contributions",
    x = "Contribution (%)",
    y = "Variable"
  ) +
  theme_minimal(base_size = 14) +
  theme(panel.grid.major.y = element_blank())




```

## Proof Of Concept: Ranger Model With SHAP

```{r}
#| label: ranger-proof-of-concept
#| cache: true

set.seed(2025)

ranger_predictors <- c(
  "quint", "unskilled", "male", "birth", "agemoth", "rural",
  "ed", "ped", "mocc", "pocc", "region"
)

ranger_dt <- copy(DRCongo)
ranger_dt[, death_factor := factor(
  ifelse(deadu5, "Death", "Alive"),
  levels = c("Alive", "Death")
)]
ranger_mm_formula <- as.formula(
  paste("~", paste(ranger_predictors, collapse = " + "))
)

ranger_mm <- model.matrix(ranger_mm_formula, data = ranger_dt)[, -1, drop = FALSE]
ranger_feature_map <- data.table(
  feature_internal = make.unique(make.names(colnames(ranger_mm))),
  feature_label = colnames(ranger_mm)
)
colnames(ranger_mm) <- ranger_feature_map$feature_internal

ranger_x_dt <- as.data.table(ranger_mm)
ranger_model_dt <- cbind(
  data.table(death_factor = ranger_dt$death_factor),
  ranger_x_dt
)

ranger_fit <- ranger(
  formula = death_factor ~ .,
  data = as.data.frame(ranger_model_dt),
  probability = TRUE,
  importance = "permutation",
  case.weights = ranger_dt$weight,
  num.trees = 1000,
  min.node.size = 50,
  seed = 2025
)

ranger_imp_dt <- merge(
  data.table(
    feature_internal = names(ranger_fit$variable.importance),
    permutation_importance = as.numeric(ranger_fit$variable.importance)
  ),
  ranger_feature_map,
  by = "feature_internal",
  all.x = TRUE
)[
  ,
  .(
    feature = fifelse(is.na(feature_label), feature_internal, feature_label),
    permutation_importance
  )
][order(-permutation_importance)]

kable(
  ranger_imp_dt[, .(feature, permutation_importance)],
  digits = 3,
  caption = "Ranger permutation importance on the Congo dataset"
) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

```{r}
#| label: ranger-shap-decomposition
#| cache: true

predict_ranger_death <- function(object, newdata) {
  scored <- predict(
    object,
    data = as.data.frame(newdata)
  )$predictions

  as.numeric(scored[, "Death"])
}

shap_background_n <- min(200, nrow(ranger_dt))
shap_eval_n <- min(300, nrow(ranger_dt))
shap_nsim <- 20

background_rows <- sort(sample.int(nrow(ranger_dt), size = shap_background_n))
eval_rows <- sort(sample.int(nrow(ranger_dt), size = shap_eval_n))

X_background <- as.data.frame(ranger_x_dt[background_rows])
X_eval <- as.data.frame(ranger_x_dt[eval_rows])

rf_shap <- fastshap::explain(
  object = ranger_fit,
  X = X_background,
  newdata = X_eval,
  pred_wrapper = predict_ranger_death,
  nsim = shap_nsim,
  adjust = TRUE
)

rf_pred_eval <- predict_ranger_death(ranger_fit, X_eval)

rf_shap_decomp <- shap_concentration_decomposition(
  shap = rf_shap,
  rank = ranger_dt$wealth[eval_rows],
  prediction = rf_pred_eval
)

rf_shap_importance_dt <- merge(
  melt(
  as.data.table(rf_shap),
  measure.vars = names(rf_shap),
  variable.name = "feature",
  value.name = "shap_value"
)[
    ,
    .(
      mean_abs_shap = mean(abs(shap_value), na.rm = TRUE),
      mean_shap = mean(shap_value, na.rm = TRUE)
    ),
    by = feature
  ],
  ranger_feature_map,
  by.x = "feature",
  by.y = "feature_internal",
  all.x = TRUE
)[
  ,
  feature := fifelse(is.na(feature_label), feature, feature_label)
][order(-mean_abs_shap)]

rf_shap_decomp_dt <- copy(as.data.table(rf_shap_decomp$contributions))
rf_shap_decomp_dt <- merge(
  rf_shap_decomp_dt,
  ranger_feature_map,
  by.x = "feature",
  by.y = "feature_internal",
  all.x = TRUE
)[
  ,
  feature := fifelse(is.na(feature_label), feature, feature_label)
]
rf_shap_decomp_dt <- rf_shap_decomp_dt[order(pct_contribution)]

rf_shap_diag_dt <- as.data.table(rf_shap_decomp$diagnostics)

kable(
  rf_shap_diag_dt,
  digits = 4,
  caption = "Diagnostics for the ranger SHAP concentration decomposition"
) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

kable(
  rf_shap_decomp_dt[, .(
    feature,
    D_k_SHAP,
    pct_contribution
  )],
  digits = 3,
  caption = "Ranger SHAP decomposition on the Congo evaluation sample"
) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

```{r}
#| label: ranger-shap-plots

ggplot(
  rf_shap_importance_dt[1:min(.N, 10)],
  aes(x = reorder(feature, mean_abs_shap), y = mean_abs_shap)
) +
  geom_col(fill = "#2C7FB8") +
  coord_flip() +
  labs(
    title = "Ranger SHAP importance",
    subtitle = "Mean absolute SHAP values on the Congo evaluation sample",
    x = "Predictor",
    y = "Mean |SHAP|"
  ) +
  theme_minimal(base_size = 12)
```


```{r}
ggplot(
  rf_shap_decomp_dt,
  aes(x = pct_contribution, y = reorder(feature, pct_contribution))
) +
  geom_col(fill = "steelblue") +
  geom_vline(xintercept = 0, color = "black", linewidth = 0.5) +
  labs(
    title = "Ranger SHAP decomposition",
    x = "Predictor",
    y = "Contribution (%)"
  ) +
  theme_minimal(base_size = 12) +
  theme(panel.grid.major.y = element_blank())
```


## Add party kit 

```{r}
#| label: source-partykit-ci

source(here("R", "partykit_ci.r"))
source(here("R", "trees_helpers_plot.R"))
```

```{r}
#| label: congo-partykit-ci-fit

load(here("data", "drc_data.rda"))
drc_v8_dt <- as.data.table(drc_data)

drc_wealth_labels <- c(
  "1" = "Poorest",
  "2" = "Poorer",
  "3" = "Middle",
  "4" = "Richer",
  "5" = "Richest"
)

drc_residence_labels <- c(
  "1" = "Urban",
  "2" = "Rural"
)

drc_collapse_occupation <- function(x) {
  x_chr <- as.character(x)
  out <- fcase(
    x_chr %in% c("4", "5"), "Agric",
    x_chr %in% c("0", "6", "9"), "HH/unskilled",
    x_chr %in% c("1", "2", "3", "7", "8"), "Other",
    default = NA_character_
  )
  factor(out, levels = c("Other", "Agric", "HH/unskilled"))
}

congo_ctree_dt <- copy(drc_v8_dt)
congo_ctree_dt[, `:=`(
  deadu5_num = fcase(
    suppressWarnings(as.numeric(b5)) == 0 &
      !is.na(suppressWarnings(as.numeric(b7))) &
      suppressWarnings(as.numeric(b7)) < 60, 1,
    suppressWarnings(as.numeric(b5)) == 1, 0,
    suppressWarnings(as.numeric(b5)) == 0 &
      !is.na(suppressWarnings(as.numeric(b7))) &
      suppressWarnings(as.numeric(b7)) >= 60, 0,
    default = NA_real_
  ),
  wealth = suppressWarnings(as.numeric(v191)) / 100000,
  quint = factor(drc_wealth_labels[as.character(v190)], levels = unname(drc_wealth_labels)),
  unskilled = factor(
    fifelse(
      as.character(v717) %in% c("0", "6", "9") | as.character(v705) %in% c("0", "6", "9"),
      "Yes", "No"
    ),
    levels = c("No", "Yes")
  ),
  male = factor(
    fifelse(as.character(b4) == "1", "Male", fifelse(as.character(b4) == "2", "Female", NA_character_)),
    levels = c("Female", "Male")
  ),
  birth = factor(
    fcase(
      suppressWarnings(as.numeric(bord)) == 1, "1st",
      suppressWarnings(as.numeric(bord)) %between% c(2, 4) &
        !is.na(suppressWarnings(as.numeric(b11))) &
        suppressWarnings(as.numeric(b11)) < 24, "2-4 short",
      suppressWarnings(as.numeric(bord)) %between% c(2, 4), "2-4 long",
      suppressWarnings(as.numeric(bord)) >= 5 &
        !is.na(suppressWarnings(as.numeric(b11))) &
        suppressWarnings(as.numeric(b11)) < 24, "5+ short",
      suppressWarnings(as.numeric(bord)) >= 5, "5+ long",
      default = NA_character_
    ),
    levels = c("1st", "2-4 short", "2-4 long", "5+ short", "5+ long")
  ),
  agemoth = suppressWarnings(as.numeric(v012)),
  rural = factor(drc_residence_labels[as.character(v025)], levels = c("Urban", "Rural")),
  ed = factor(
    fifelse(
      suppressWarnings(as.numeric(v133)) == 0, "No edu",
      fifelse(!is.na(suppressWarnings(as.numeric(v133))), "Any edu", NA_character_)
    ),
    levels = c("Any edu", "No edu")
  ),
  ped = factor(
    fifelse(
      as.character(v701) == "0", "No edu",
      fifelse(as.character(v701) %in% c("1", "2", "3"), "Any edu", NA_character_)
    ),
    levels = c("Any edu", "No edu")
  ),
  mocc = drc_collapse_occupation(v717),
  pocc = drc_collapse_occupation(v705),
  reg = factor(sprintf("Region %02d", suppressWarnings(as.integer(v024)))),
  sample_weight = suppressWarnings(as.numeric(v005)) / 1000000
)]

congo_ctree_dt <- na.omit(
  congo_ctree_dt[, .(
    wealth, deadu5_num, quint, unskilled, male, birth, agemoth, rural,
    ed, ped, mocc, pocc, reg, sample_weight
  )]
)

congo_char_cols <- names(congo_ctree_dt)[vapply(congo_ctree_dt, is.character, logical(1))]
if (length(congo_char_cols) > 0L) {
  congo_ctree_dt[, (congo_char_cols) := lapply(.SD, factor), .SDcols = congo_char_cols]
}

congo_ctree_dt[, case_weight := as_caseweights(sample_weight, scale = 10000L)]
congo_ctree_dt <- congo_ctree_dt[case_weight > 0]

congo_ctree_ci_grid <- ctree_ci_control_grid(
  mincriterion = c(0.05, 0.09, 0.15),
  minsplit = c(50L, 100L,  200L),
  minbucket = c(100L, 200L, 300L),
  minprob = c(0.001, 0.005, 0.01),
  maxdepth = c( 4L, 5L)
)

# quint + reg
congo_ctree_ci_cv <- tune_ctree_ci_controls(
  formula = cbind(wealth, deadu5_num) ~  unskilled + male + birth + agemoth + rural +
    ed + ped + mocc + pocc + reg,
  data = congo_ctree_dt,
  rank_name = "wealth",
  outcome_name = "deadu5_num",
  weights = congo_ctree_dt$case_weight,
  type = "CI",
  control_grid = congo_ctree_ci_grid,
  v = 5,
  strata = "deadu5_num",
  metric = "validation_gain",
  fit_best = TRUE
)

congo_ctree_ci_best_params <- congo_ctree_ci_cv$best_params
congo_ctree_ci_fit <- congo_ctree_ci_cv$best_fit

congo_ctree_node_stats <- tree_build_terminal_stats(
  fit = congo_ctree_ci_fit,
  data = congo_ctree_dt,
  stat_funs = list(
    n = function(dt) nrow(dt),
    death_rate = function(dt) weighted.mean(dt$deadu5_num, dt$case_weight),
    mean_wealth = function(dt) weighted.mean(dt$wealth, dt$case_weight)
  )
)

congo_ctree_ci_best_params
```

```{r}
#| label: congo-partykit-ci-cv-summary

kable(
  congo_ctree_ci_cv$summary,
  digits = 4,
  caption = "Cross-validated tuning summary for the DRC v8 CI-based partykit tree"
) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

```{r}
#| label: congo-partykit-ci-plot
#| fig.width: 20
#| fig.height: 10

congo_var_labels <- c(
 # quint = "Wealth group",
  unskilled = "Low-skill HH",
  male = "Child sex",
  birth = "Birth group",
  agemoth = "Mother age",
  rural = "Residence",
  ed = "Mother education",
  ped = "Partner education",
  mocc = "Mother occupation",
  pocc = "Partner occupation",
  reg = "Province"
)

if (length(nodeids(congo_ctree_ci_fit, terminal = TRUE)) > 1L) {
  plot(
    congo_ctree_ci_fit,
    gp = gpar(fontsize = 6.5),
    inner_panel = tree_inner_panel_labeled,
    ip_args = list(
      var_labels = congo_var_labels,
      id = FALSE
    ),
    terminal_panel = tree_terminal_panel_stats,
    tp_args = list(
      stats_dt = congo_ctree_node_stats,
      stat_labels = c(
        n = "n",
        death_rate = "death rate",
        mean_wealth = "mean wealth"
      ),
      stat_formatters = list(
        n = function(x) format(x, big.mark = ",", scientific = FALSE),
        death_rate = function(x) sprintf("%.2f%%", 100 * x),
        mean_wealth = function(x) format(round(x, 2), nsmall = 2)
      ),
      width_lines = 10.5,
      height_lines = 3.2
    ),
    edge_panel = tree_edge_panel_compact,
    ep_args = list(
      var_labels = congo_var_labels,
      max_items = 3,
      max_chars = 24,
      plural_overrides = c(Region = "regions")
    ),
    drop_terminal = FALSE,
    tnex = 0.85
  )
} else {
  plot.new()
  text(0.5, 0.56, "No split was retained under the current partykit control settings.")
  text(
    0.5, 0.44,
    paste0(
      "Root death rate = ",
      sprintf("%.2f%%", 100 * congo_ctree_node_stats$death_rate[1]),
      "; mean wealth = ",
      format(round(congo_ctree_node_stats$mean_wealth[1], 2), nsmall = 2)
    )
  )
}
```


## kenya analysis 

```{r}
#| label: kenya-partykit-ci-fit

load(here("data", "kenya_data.rda"))
kenya_dt <- as.data.table(kenya_data)

labeled_factor <- function(x, labels) {
  factor(labels[as.character(x)], levels = unique(unname(labels)))
}

wealth_labels <- c(
  "1" = "Poorest",
  "2" = "Poorer",
  "3" = "Middle",
  "4" = "Richer",
  "5" = "Richest"
)

residence_labels <- c(
  "1" = "Urban",
  "2" = "Rural"
)


region_labels <- c(
  "1" = "Mombasa",
  "2" = "Kwale",
  "3" = "Kilifi",
  "4" = "Tana River",
  "5" = "Lamu",
  "6" = "Taita Taveta",
  "7" = "Garissa",
  "8" = "Wajir",
  "9" = "Mandera",
  "10" = "Marsabit",
  "11" = "Isiolo",
  "12" = "Meru",
  "13" = "Tharaka-Nithi",
  "14" = "Embu",
  "15" = "Kitui",
  "16" = "Machakos",
  "17" = "Makueni",
  "18" = "Nyandarua",
  "19" = "Nyeri",
  "20" = "Kirinyaga",
  "21" = "Murang'a",
  "22" = "Kiambu",
  "23" = "Turkana",
  "24" = "West Pokot",
  "25" = "Samburu",
  "26" = "Trans Nzoia",
  "27" = "Uasin Gishu",
  "28" = "Elgeyo-Marakwet",
  "29" = "Nandi",
  "30" = "Baringo",
  "31" = "Laikipia",
  "32" = "Nakuru",
  "33" = "Narok",
  "34" = "Kajiado",
  "35" = "Kericho",
  "36" = "Bomet",
  "37" = "Kakamega",
  "38" = "Vihiga",
  "39" = "Bungoma",
  "40" = "Busia",
  "41" = "Siaya",
  "42" = "Kisumu",
  "43" = "Homa Bay",
  "44" = "Migori",
  "45" = "Kisii",
  "46" = "Nyamira",
  "47" = "Nairobi"
)


collapse_occupation <- function(x) {
  x_chr <- as.character(x)
  out <- fcase(
    x_chr %in% c("4", "5"), "Agric",
    x_chr %in% c("0", "6", "9"), "HH/unskilled",
    x_chr %in% c("1", "2", "3", "7", "8"), "Other",
    default = NA_character_
  )
  factor(out, levels = c("Other", "Agric", "HH/unskilled"))
}

kenya_ctree_dt <- copy(kenya_dt)
kenya_ctree_dt[, `:=`(
  deadu5_num = fcase(
    suppressWarnings(as.numeric(b5)) == 0 &
      !is.na(suppressWarnings(as.numeric(b7))) &
      suppressWarnings(as.numeric(b7)) < 60, 1,
    suppressWarnings(as.numeric(b5)) == 1, 0,
    suppressWarnings(as.numeric(b5)) == 0 &
      !is.na(suppressWarnings(as.numeric(b7))) &
      suppressWarnings(as.numeric(b7)) >= 60, 0,
    default = NA_real_
  ),
  wealth = suppressWarnings(as.numeric(v190)),
  quint = factor(wealth_labels[as.character(v190)], levels = unname(wealth_labels)),
  unskilled = factor(
    fifelse(
      as.character(v717) %in% c("0", "6", "9") | as.character(v705) %in% c("0", "6", "9"),
      "Yes", "No"
    ),
    levels = c("No", "Yes")
  ),
  male = factor(
    fifelse(as.character(b4) == "1", "Male", fifelse(as.character(b4) == "2", "Female", NA_character_)),
    levels = c("Female", "Male")
  ),
  birth = factor(
    fcase(
      suppressWarnings(as.numeric(bord)) == 1, "1st",
      suppressWarnings(as.numeric(bord)) %between% c(2, 4) &
        !is.na(suppressWarnings(as.numeric(b11))) &
        suppressWarnings(as.numeric(b11)) < 24, "2-4 short",
      suppressWarnings(as.numeric(bord)) %between% c(2, 4), "2-4 long",
      suppressWarnings(as.numeric(bord)) >= 5 &
        !is.na(suppressWarnings(as.numeric(b11))) &
        suppressWarnings(as.numeric(b11)) < 24, "5+ short",
      suppressWarnings(as.numeric(bord)) >= 5, "5+ long",
      default = NA_character_
    ),
    levels = c("1st", "2-4 short", "2-4 long", "5+ short", "5+ long")
  ),
  agemoth = suppressWarnings(as.numeric(v012)),
  rural = factor(residence_labels[as.character(v025)], levels = c("Urban", "Rural")),
  ed = factor(
    fifelse(
      as.character(v149) == "0", "No edu",
      fifelse(as.character(v149) %in% c("1", "2", "3", "4", "5"), "Any edu", NA_character_)
    ),
    levels = c("Any edu", "No edu")
  ),
  ped = factor(
    fifelse(
      as.character(v701) == "0", "No edu",
      fifelse(as.character(v701) %in% c("1", "2", "3"), "Any edu", NA_character_)
    ),
    levels = c("Any edu", "No edu")
  ),
  mocc = collapse_occupation(v717),
  pocc = collapse_occupation(v705),
  reg = labeled_factor(v024, region_labels),
  sample_weight = suppressWarnings(as.numeric(v005)) / 1000000
)]

kenya_ctree_dt <- na.omit(
  kenya_ctree_dt[, .(
    wealth, deadu5_num, quint, unskilled, male, birth, agemoth, rural,
    ed, ped, mocc, pocc, reg, sample_weight
  )]
)

kenya_char_cols <- names(kenya_ctree_dt)[vapply(kenya_ctree_dt, is.character, logical(1))]
if (length(kenya_char_cols) > 0L) {
  kenya_ctree_dt[, (kenya_char_cols) := lapply(.SD, factor), .SDcols = kenya_char_cols]
}

kenya_ctree_dt[, case_weight := as_caseweights(sample_weight, scale = 10000L)]
kenya_ctree_dt <- kenya_ctree_dt[case_weight > 0]

kenya_ctree_ci_grid <- ctree_ci_control_grid(
  mincriterion = c(0.05, 0.09, 0.15),
  minsplit = c(100L, 200L),
  minbucket = c(100L, 200L),
  minprob = c(0.001, 0.005),
  maxdepth = c(2L, 4L, 5L)
)

kenya_ctree_ci_cv <- tune_ctree_ci_controls(
  formula = cbind(wealth, deadu5_num) ~ quint + unskilled + male + birth + agemoth + rural +
    ed + ped + mocc + pocc + reg,
  data = kenya_ctree_dt,
  rank_name = "wealth",
  outcome_name = "deadu5_num",
  weights = kenya_ctree_dt$case_weight,
  type = "CI",
  control_grid = kenya_ctree_ci_grid,
  v = 5,
  strata = "deadu5_num",
  metric = "validation_gain",
  fit_best = TRUE
)

kenya_ctree_ci_best_params <- kenya_ctree_ci_cv$best_params
kenya_ctree_ci_fit <- kenya_ctree_ci_cv$best_fit

kenya_ctree_node_stats <- tree_build_terminal_stats(
  fit = kenya_ctree_ci_fit,
  data = kenya_ctree_dt,
  stat_funs = list(
    n = function(dt) nrow(dt),
    death_rate = function(dt) weighted.mean(dt$deadu5_num, dt$case_weight),
    mean_wealth = function(dt) weighted.mean(dt$wealth, dt$case_weight)
  )
)

kenya_ctree_ci_best_params
```

```{r}
#| label: kenya-partykit-ci-cv-summary

kable(
  kenya_ctree_ci_cv$summary,
  digits = 4,
  caption = "Cross-validated tuning summary for the Kenya CI-based partykit tree"
) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

```{r}
#| label: kenya-partykit-ci-plot
#| fig.width: 20
#| fig.height: 10

kenya_var_labels <- c(
  quint = "Wealth group",
  unskilled = "Low-skill HH",
  male = "Child sex",
  birth = "Birth group",
  agemoth = "Mother age",
  rural = "Residence",
  ed = "Mother education",
  ped = "Partner education",
  mocc = "Mother occupation",
  pocc = "Partner occupation",
  reg = "Region"
)

if (length(nodeids(kenya_ctree_ci_fit, terminal = TRUE)) > 1L) {
  plot(
    kenya_ctree_ci_fit,
    gp = gpar(fontsize = 6.5),
    inner_panel = tree_inner_panel_labeled,
    ip_args = list(
      var_labels = kenya_var_labels,
      id = FALSE
    ),
    terminal_panel = tree_terminal_panel_stats,
    tp_args = list(
      stats_dt = kenya_ctree_node_stats,
      stat_labels = c(
        n = "n",
        death_rate = "death rate",
        mean_wealth = "mean wealth"
      ),
      stat_formatters = list(
        n = function(x) format(x, big.mark = ",", scientific = FALSE),
        death_rate = function(x) sprintf("%.2f%%", 100 * x),
        mean_wealth = function(x) format(round(x, 2), nsmall = 2)
      ),
      width_lines = 10.5,
      height_lines = 3.2
    ),
    edge_panel = tree_edge_panel_compact,
    ep_args = list(
      var_labels = kenya_var_labels,
      max_items = 3,
      max_chars = 24,
      plural_overrides = c(Region = "regions")
    ),
    drop_terminal = FALSE,
    tnex = 0.85
  )
} else {
  plot.new()
  text(0.5, 0.56, "No split was retained under the current partykit control settings.")
  text(
    0.5, 0.44,
    paste0(
      "Root death rate = ",
      sprintf("%.2f%%", 100 * kenya_ctree_node_stats$death_rate[1]),
      "; mean wealth = ",
      format(round(kenya_ctree_node_stats$mean_wealth[1], 2), nsmall = 2)
    )
  )
}
```


## DRC version 8 survey
